server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9094,localhost:9095,localhost:9096

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all
      retries: 5

    properties:
      enable.idempotence: true